---
title: "venn_diagrams"
author: "Your Name"
date: "2021-08-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


In this diagram, we plot the overlap between blocks containing at least one variant in  the 500 kb blocks delimited by UKBB and MVP.

First, read in the data
```{r}
mvp=read.table("~/Dropbox/mash_materials/blocks_mvp.txt",header = T)
ukbb=read.table("~/Dropbox/mash_materials/blocks_ukbb.txt",header = T)
mtag=read.table("~/Dropbox/mash_materials/blocks_mtag.txt",header = T)
old=read.table("~/Dropbox/mash_materials/blocks_original_data.txt",header = T)
```

Now make the plots!

```{r}
library("eulerr")
fit.hdl=euler(list("MVP:mash"=which(mvp$hdl==1),"UKBB:mash"=which(ukbb$hdl==1),"MVP:uni"=which(old$hdl==1),"MVP:mtag"=which(mtag$hdl==1)))
fit.ldl=euler(list("MVP:mash"=which(mvp$ldl==1),"UKBB:mash"=which(ukbb$ldl==1),"MVP:uni"=which(old$ldl==1),"MVP:mtag"=which(mtag$ldl==1)))
fit.tg=euler(list("MVP:mash"=which(mvp$tg==1),"UKBB:mash"=which(ukbb$tg==1),"MVP:uni"=which(old$tg==1),"MVP:mtag"=which(mtag$tg==1)))


plot(fit.hdl,
     fills = c("steelblue1","tomato1","lightgreen"),
     edges = T,
     #cex. = 200,
     quantities = list(cex = 2),adjust_labels = F,
     main="HDL-C",labels=list(cex=2))

plot(fit.ldl,
     fills = c("steelblue1","tomato1","lightgreen"),
     edges = T,
     #cex. = 200,
     quantities = list(cex = 2),adjust_labels = F,
     main="LDL-C",labels=list(cex=2))

plot(fit.tg,
     fills = c("steelblue1","tomato1","lightgreen"),
     edges = T,
     #cex. = 200,
     quantities = list(cex = 2),adjust_labels = F,
     main="TG",labels=list(cex=2))


```